version: '3'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    platform: linux/amd64
    environment:
      - MARIADB_USER=local_test_user
      - MARIADB_DATABASE=local_db
      - MARIADB_PASSWORD=LOCAL_PWD_CHANGE_IN_PROD
      - MARIADB_ROOT_PASSWORD=LOCAL_ROOT_PWD_CHANGE_IN_PROD

  backend:
    tty: true
    image: backend:latest
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=local_test_user
      - DB_DATABASE=local_db
      - DB_PASSWORD=LOCAL_PWD_CHANGE_IN_PROD
    depends_on:
      - mariadb
    volumes:
      - ../../backend:/usr/src/backend
    ports:
      - 8000:8000

  frontend:
    tty: true
    image: frontend-dev:latest
    command: npm run start
    volumes:
      - ../../frontend:/home/frontend/
    ports:
      - 3000:3000
