version: '3'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  backend:
    # runs on port 8000
    tty: true
    image: docker.io/bitnami/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mariadb
    volumes:
      # take the code
      - ../../backend:/app

  frontend:
    image: ghcr.io/yang170/frontend:latest
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    depends_on:
      - mariadb
      - backend
    
  nginx:
    image: ghcr.io/yang170/nginx:latest
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend
      - frontend
      - mariadb
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${FULL_CHAIN_PATH}:/etc/nginx/certs/fullchain.pem
      - ${PRIV_KEY_PATH}:/etc/nginx/certs/privkey.pem
