version: '3'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_USER=local_test_user
      - MARIADB_DATABASE=local_db
      - MARIADB_PASSWORD=LOCAL_PWD_CHANGE_IN_PROD
      - MARIADB_ROOT_PASSWORD=LOCAL_ROOT_PWD_CHANGE_IN_PROD

  backend:
    tty: true
    image: backend:0.0.1
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=local_test_user
      - DB_DATABASE=local_db
      - DB_PASSWORD=LOCAL_PWD_CHANGE_IN_PROD
    depends_on:
      - mariadb
    ports:
      - 8000:8000

  # backend:
  #   tty: true
  #   image: docker.io/bitnami/laravel:8
  #   environment:
  #     - DB_HOST=mariadb
  #     - DB_USERNAME=local_test_user
  #     - DB_DATABASE=local_db
  #     - DB_PASSWORD=LOCAL_PWD_CHANGE_IN_PROD
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ../../backend/:/app
