name: CI Docker Image for the Frontend

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm ci

      - name: build
        working-directory: ./frontend
        run: |
          npm run build

      - name: temporarily save build files
        working-directory: ./frontend
        uses: actions/upload-artifact@v3
        with:
          name: npm-build-artifact
          path: build
          retention-days: 1

  build_frontend_docker_image:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - uses: actions/checkout@v3

      - name: retrieve build files
        working-directory: ./frontend
        uses: actions/download-artifact@v3
        with:
          name: npm-build-artifact
          path: build

      - name: Build the Docker image for the frontend
        run: docker build . --file ./conf/dockerfiles/Dockerfile.frontend --tag frontend:latest
